x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  traefik:
    <<: *default-logging
    image: traefik:v3.7.13
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/traefik/letsencrypt:/letsencrypt
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=320689555+losi57304@users.noreply.github.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    labels:
      - glance.name=Traefik
      - glance.icon=sh:traefik

  rathole:
    <<: *default-logging
    image: rapiz1/rathole:v0.5.0
    container_name: rathole
    ports:
      - 2333:2333
      - 127.0.0.1:11434:11434
    volumes:
      - ./rathole-config.toml:/app/config.toml:ro
    restart: unless-stopped
    command:
      - --server
      - /app/config.toml
    labels:
      - glance.name=Rathole
      - glance.icon=sh:rathole.png

networks:
  default:
    name: proxy
    external: true
