x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  beszel:
    <<: *default-logging
    container_name: beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - /run/beszel:/beszel_socket
      - /srv/beszel/data:/beszel_data
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']

  beszel-agent:
    <<: *default-logging
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.19.0
    restart: unless-stopped
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=${BESZEL_KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_TOKEN}
    volumes:
      - /run/beszel:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ['CMD', '/agent', 'health']

  caddy:
    <<: *default-logging
    container_name: caddy
    image: caddy:2.11.4
    restart: unless-stopped
    network_mode: host
    volumes:
      - /run/continuwuity:/run/continuwuity
      - /run/dufs:/run/dufs
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/caddy/config:/config
      - /srv/caddy/data:/data
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider http://localhost:2019/config || exit 1']

  continuwuity:
    <<: *default-logging
    container_name: continuwuity
    image: forgejo.ellis.link/continuwuation/continuwuity:sha-c6f2c5e-maxperf
    restart: unless-stopped
    command:
      - /sbin/conduwuit
    environment:
      - CONTINUWUITY_ALLOW_REGISTRATION=${CONTINUWUITY_ALLOW_REGISTRATION}
      - CONTINUWUITY_CONFIG=/etc/continuwuity.toml
      - CONTINUWUITY_TURN__SECRET=${CONTINUWUITY_TURN__SECRET}
    volumes:
      - /run/continuwuity:/run/continuwuity
      - ./continuwuity.toml:/etc/continuwuity.toml:ro
      - /srv/continuwuity:/var/lib/continuwuity
    healthcheck:
      test: ['CMD-SHELL', 'test -S /run/continuwuity/continuwuity.sock || exit 1']

  coturn:
    <<: *default-logging
    container_name: coturn
    image: coturn/coturn:4.18.0
    restart: unless-stopped
    command:
      - -n
      - --log-file=stdout
      - --fingerprint
      - --lt-cred-mech
      - --use-auth-secret
      - --static-auth-secret=${COTURN_STATIC_AUTH_SECRET}
      - --realm=continuwuity.ocd.beauty
    network_mode: host
    healthcheck:
      test: ['CMD-SHELL', 'turnutils_stunclient -p 3478 localhost || exit 1']

  dufs:
    <<: *default-logging
    container_name: dufs
    image: sigoden/dufs:v0.46.0
    restart: unless-stopped
    command:
      - -b
      - /run/dufs/dufs.sock
      - -a
      - ${DUFS_USERNAME}:${DUFS_PASSWORD}@/:rw
      - -A
      - /music
    volumes:
      - /run/dufs:/run/dufs
      - /srv/gonic/music:/music
    healthcheck:
      test: ['CMD-SHELL', 'test -S /run/dufs/dufs.sock || exit 1']

  gonic:
    <<: *default-logging
    container_name: gonic
    image: sentriz/gonic:8df10c3
    restart: unless-stopped
    environment:
      - GONIC_MUSIC_PATH=/music
      - GONIC_PODCAST_PATH=/podcast
      - GONIC_PLAYLISTS_PATH=/playlists
      - GONIC_CACHE_PATH=/cache
      - GONIC_DB_PATH=/data/gonic.db
    ports:
      - 127.0.0.1:81:80
    volumes:
      - /srv/gonic/music:/music
      - /srv/gonic/data:/data
      - /srv/gonic/podcast:/podcast
      - /srv/gonic/playlists:/playlists
      - /srv/gonic/cache:/cache
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider http://localhost:80 || exit 1']
