[global]
allow_federation = false
database_path = "/var/lib/continuwuity"
request_ip_source = "x_forwarded_for"
server_name = "continuwuity.ocd.beauty"
unix_socket_path = "/run/continuwuity/continuwuity.sock"
unix_socket_perms = 0o777

[global.well_known]
server = "continuwuity.ocd.beauty:443"
client = "https://continuwuity.ocd.beauty"

[global.matrix_rtc]
foci = [
    { livekit_service_url = "https://livekit-server.continuwuity.ocd.beauty", type = "livekit" }
]
