[global]
allow_federation = false
database_path = "/var/lib/continuwuity"
request_ip_source = "x_forwarded_for"
server_name = "continuwuity.ocd.beauty"
turn_uris = [
    "turn:continuwuity.ocd.beauty:3478?transport=udp",
    "turn:continuwuity.ocd.beauty:3478?transport=tcp"
]
unix_socket_path = "/run/continuwuity/continuwuity.sock"
unix_socket_perms = 0o777

[global.well_known]
client = "https://continuwuity.ocd.beauty"
server = "continuwuity.ocd.beauty:443"
support_email = "320689555+losi57304@users.noreply.github.com"
