x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  forgejo:
    <<: *default-logging
    image: codeberg.org/forgejo/forgejo:16.0.5
    container_name: forgejo
    volumes:
      - /srv/forgejo/data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - glance.icon=sh:forgejo
      - glance.name=Forgejo
      - glance.url=https://git.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.ocd.beauty`)
      - traefik.http.routers.gitea.tls.certresolver=letsencrypt
      - traefik.http.services.gitea.loadbalancer.server.port=3000
