x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  photos-postgres:
    <<: *default-logging
    container_name: photos-postgres
    image: postgres:18.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ente_db
      - PGDATA=/var/lib/postgresql/18/data
    volumes:
      - /srv/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

  photos-garage:
    <<: *default-logging
    container_name: photos-garage
    image: dxflrs/garage:v2.4.1
    restart: unless-stopped
    environment:
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - /srv/garage/meta:/var/lib/garage/meta
      - /srv/garage/data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "/garage", "-c", "/etc/garage.toml", "status"]

  photos-ente-server:
    <<: *default-logging
    container_name: photos-ente-server
    image: ghcr.io/ente/server:163f45c26f130090abed03649530f53d2d976565
    restart: unless-stopped
    environment:
      - ENTE_DB_HOST=photos-postgres
      - ENTE_DB_PASSWORD=${POSTGRES_PASSWORD}
      - BUCKET_KEY=${BUCKET_KEY}
      - BUCKET_SECRET=${BUCKET_SECRET}
    volumes:
      - ./museum.yaml:/museum.yaml:ro
      - /srv/museum/data:/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
    depends_on:
      - photos-postgres
      - photos-garage

networks:
  default:
    name: proxy
    external: true
