x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  vaultwarden-server:
    <<: *default-logging
    image: vaultwarden/server:1.37.3
    container_name: vaultwarden-server
    environment:
      - DOMAIN=https://secret.ocd.beauty
    volumes:
      - /srv/vaultwarden-server/data:/data
    restart: unless-stopped
    labels:
      - glance.icon=sh:vaultwarden-light
      - glance.name=Vaultwarden
      - glance.url=https://secret.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`secret.ocd.beauty`)
      - traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

networks:
  default:
    external: true
    name: proxy
