x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  glance:
    <<: *default-logging
    image: glanceapp/glance:v0.8.6
    container_name: glance
    environment:
      - GLANCE_AUTH_PASSWORD=${GLANCE_AUTH_PASSWORD}
      - GLANCE_AUTH_SECRET_KEY=${GLANCE_AUTH_SECRET_KEY}
      - GLANCE_WEATHER_LOCATION=${GLANCE_WEATHER_LOCATION}
    volumes:
      - /srv/glance/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ./glance.yaml:/app/config/glance.yml:ro
    restart: unless-stopped
    labels:
      - glance.icon=sh:glance-light
      - glance.name=Glance
      - glance.url=https://home.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.glance.entrypoints=websecure
      - traefik.http.routers.glance.rule=Host(`home.ocd.beauty`)
      - traefik.http.routers.glance.tls.certresolver=letsencrypt
      - traefik.http.services.glance.loadbalancer.server.port=8080

networks:
  default:
    external: true
    name: proxy
