x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  glance:
    <<: *default-logging
    container_name: glance
    image: glanceapp/glance:v0.8.6
    restart: unless-stopped
    environment:
      - GLANCE_SECRET_KEY=${GLANCE_SECRET_KEY}
      - GLANCE_PASSWORD=${GLANCE_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/glance/config:/app/config
      - ./glance.yaml:/app/config/glance.yml
      - ./styles.css:/assets/styles.css
      - ./wallpapers.jpg:/assets/wallpapers.jpg
    labels:
      - glance.name=Glance
      - glance.icon=sh:glance
      - traefik.enable=true
      - traefik.http.routers.glance.rule=Host(`home.ocd.beauty`)
      - traefik.http.routers.glance.entrypoints=websecure
      - traefik.http.routers.glance.tls.certresolver=letsencrypt
      - traefik.http.services.glance.loadbalancer.server.port=8080

networks:
  default:
    name: proxy
    external: true
