x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  authelia:
    <<: *default-logging
    image: authelia/authelia:4.39.28
    container_name: authelia
    environment:
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    expose:
      - 9091
    volumes:
      - /srv/authelia/config:/config
      - ./configuration.yaml:/config/configuration.yml
      - ./users_database.yaml:/config/users_database.yaml
    restart: unless-stopped
    labels:
      - glance.icon=sh:authelia-light
      - glance.name=Authelia
      - glance.url=https://authentication.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`authentication.ocd.beauty`)
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email

networks:
  default:
    external: true
    name: proxy
