x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  woodpecker-server:
    <<: *default-logging
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    environment:
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://ci.ocd.beauty
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://git.ocd.beauty
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_GRPC_SECRET=${WOODPECKER_GRPC_SECRET}
    volumes:
      - /srv/woodpecker/server/data:/var/lib/woodpecker
    restart: unless-stopped
    labels:
      - glance.name=Woodpecker CI
      - glance.icon=sh:woodpecker-ci
      - glance.id=woodpecker-server
      - glance.url=https://ci.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.woodpecker-server.rule=Host(`ci.ocd.beauty`)
      - traefik.http.routers.woodpecker-server.entrypoints=websecure
      - traefik.http.routers.woodpecker-server.tls.certresolver=letsencrypt
      - traefik.http.services.woodpecker-server.loadbalancer.server.port=8000

  woodpecker-agent:
    <<: *default-logging
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    depends_on:
      - woodpecker-server
    environment:
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_GRPC_SECRET=${WOODPECKER_GRPC_SECRET}
    volumes:
      - /srv/woodpecker/agent/config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command:
      - agent
    labels:
      - glance.parent=woodpecker-server
      - glance.name=woodpecker-agent
