users:
    losi57304:
        displayname: ENC[AES256_GCM,data:EdVd5LdPCg6F,iv:jcpWOKdoyfd1ifbfpvJrb0ShBZALAfegQd7Wque9hKI=,tag:vMxAP+MUQR4SBB92u8EMig==,type:str]
        password: ENC[AES256_GCM,data:8nH6DYcswAyyUd3wOPjuin6/FvRa9T81bWM2EAxOVBswAL72b+ml5MpOk3tqnNhTGyuOOT3uhl48TnudS7Hv3EPver+pVQzi0Q8n+Z0FQE5hhCXLq8YXceM6hOEpUvd0sw==,iv:v3u2kV4tvk/3nTmIBd5CxR7C0OvBSLv+ATHk8UzxAnM=,tag:UjYngcL5HuhEWaKWBndOeg==,type:str]
        email: ENC[AES256_GCM,data:Cx9ovNRvJj4K7KEhZjqJ2M59Osix53P242XYUzQDzIPKwr7qI4hcZBBnS8Y=,iv:QZiJJ83TQbPJ6V9ew+Q1EONonzAiq+wOnjV8NQSUKjs=,tag:2NlOeScrkaQSoq944fbDJw==,type:str]
        groups:
            - ENC[AES256_GCM,data:C0WxXZjG,iv:ituKl3Mb2JKBIfUXF1Wbyi5ArRPFBRZxVfZghXvAS6Q=,tag:DON19xkNFMaN4IXYc+SIQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRFQ2aS9hWHMxZ1l6TFdv
            dEtLcUhnMEVEMXdGcVhoenl4TFpqQUxMenh3Cks0MjVIR0NIZmVVcUwwZS8rb3ds
            UTVBTHRnRFZYa0JWMy9CeDE4TnZKMUEKLS0tIEhNQjdGZlhzRXdFeGZOUnVnSFRO
            UnB3Vnd4ZGZrZGE0OHp0QTV2UHZhNkUKgII4M/ch/W+oMncxN3OA4dKnCItO3vOO
            viAAHQqpRHPyp7/mWhpEfS4s9PQSy2tiUKtbwrSPDoH8Zz3w8qxqtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19tlnwt3yu46a84hlqlwcc9nskp5g7uql7r8r97xgklz2s8gz4enshndgel
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WjFuYWZMZmpZWGxVVXNN
            WjVEa1paUVVOLzk1M1VaakhiT0MwMWl3Y2dFCnRUN3hiRGFkSUxCNkQvdnBLSGlM
            RUhBNk5hZ29hdDJwMU50K1BYK09sSUEKLS0tIFFyZERvenZqbjdkRlF4Z1pFZ1cz
            YnN5SDdOTjM2dWdjTkpjcWtJSU9tdFkKkRJPku4LRnFHDjasESs9weUzOkV/lzzx
            aLWmHP1rylc0AUPwVHo0iEZIU3mpv1Zz/VkFlusYr984BXPys3TSaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12kmps9wd8x8jj5t8v0hrmy7p0n85t6s0xuu084jye6tweulh94qq4w8yr4
    lastmodified: "2026-09-21T21:24:08Z"
    mac: ENC[AES256_GCM,data:FHbxCbi/8QHXdk4MJM47KeBR7uO/loqfJveE0h3LPR8gmWhOJinrQJbPG8R36wogevpcIiQQ8atRHsOEpmRiG8gVNHo0ZxO4mtnhzWfW9j0BKbH0+GwTb4aRBYKiYNZSMQgtvLx4D6MOMgI0ciUGeIsFeRTtUHeROpYQYVMWUPk=,iv:BZOhsCVYirjJYkn//23SLTJxb0IClKcv6KvzyCRcCW4=,tag:u4Nno/sstIFkrGSiHOPrBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
