x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  jitsi-prosody:
    <<: *default-logging
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=0
      - GLOBAL_MODULES=
      - GLOBAL_CONFIG=
      - LOG_LEVEL=warn
      - PUBLIC_URL=https://meetings.ocd.beauty
      - TZ=UTC
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - /srv/jitsi-prosody/config:/config
      - /srv/jitsi-prosody/prosody-plugins-custom:/prosody-plugins-custom
    restart: unless-stopped
    labels:
      - glance.name=jitsi-prosody
      - glance.parent=jitsi-web

  jitsi-jicofo:
    <<: *default-logging
    image: jitsi/jicofo:stable
    container_name: jitsi-jicofo
    depends_on:
      - jitsi-prosody
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=0
      - XMPP_SERVER=jitsi-prosody
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JICOFO_ENABLE_BRIDGE_PRESENCE=1
      - LOG_LEVEL=warn
      - TZ=UTC
    volumes:
      - /srv/jitsi-jicofo/jicofo:/config
    restart: unless-stopped
    labels:
      - glance.name=jitsi-jicofo
      - glance.parent=jitsi-web

  jitsi-jvb:
    <<: *default-logging
    image: jitsi/jvb:stable
    container_name: jitsi-jvb
    depends_on:
      - jitsi-prosody
    ports:
      - 10000:10000/udp
    environment:
      - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}
      - XMPP_SERVER=jitsi-prosody
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_PORT=10000
      - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
      - LOG_LEVEL=warn
      - TZ=UTC
    volumes:
      - /srv/jitsi-jvb/config:/config
    restart: unless-stopped
    labels:
      - glance.name=jitsi-jvb
      - glance.parent=jitsi-web

  jitsi-web:
    <<: *default-logging
    image: jitsi/web:stable
    container_name: jitsi-web
    depends_on:
      - jitsi-prosody
      - jitsi-jvb
    environment:
      - PUBLIC_URL=https://meetings.ocd.beauty
      - XMPP_SERVER=jitsi-prosody
      - DISABLE_HTTPS=1
      - ENABLE_HTTP_REDIRECT=0
      - TZ=UTC
    volumes:
      - /srv/jitsi-web/config:/config
      - /srv/jitsi-web/crontabs:/var/spool/cron/crontabs
    restart: unless-stopped
    labels:
      - glance.icon=sh:jitsi-light
      - glance.id=jitsi-web
      - glance.name=Jitsi
      - traefik.enable=true
      - traefik.http.routers.jitsi.rule=Host(`meetings.ocd.beauty`)
      - traefik.http.routers.jitsi.entrypoints=websecure
      - traefik.http.routers.jitsi.tls.certresolver=letsencrypt
      - traefik.http.services.jitsi.loadbalancer.server.port=80
      - traefik.http.middlewares.jitsi-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.jitsi.middlewares=jitsi-headers

networks:
  default:
    external: true
    name: proxy
