x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  vikunja:
    <<: *default-logging
    image: vikunja/vikunja:2.6.0
    container_name: vikunja
    environment:
      - VIKUNJA_SERVICE_PUBLICURL=https://task.ocd.beauty
      - VIKUNJA_SERVICE_SECRET=${VIKUNJA_SERVICE_SECRET}
      - VIKUNJA_DATABASE_PATH=/db/vikunja.db
    volumes:
      - /srv/vikunja/files:/app/vikunja/files
      - /srv/vikunja/db:/db
    restart: unless-stopped
    labels:
      - glance.icon=sh:vikunja-light
      - glance.name=Vikunja
      - glance.url=https://task.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.vikunja.entrypoints=websecure
      - traefik.http.routers.vikunja.rule=Host(`task.ocd.beauty`)
      - traefik.http.routers.vikunja.tls.certresolver=letsencrypt
      - traefik.http.services.vikunja.loadbalancer.server.port=3456

networks:
  default:
    external: true
    name: proxy
