x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  continuwuity:
    <<: *default-logging
    image: forgejo.ellis.link/continuwuation/continuwuity:sha-c6f2c5e-maxperf
    container_name: continuwuity
    environment:
      - CONTINUWUITY_ALLOW_REGISTRATION=${CONTINUWUITY_ALLOW_REGISTRATION}
      - CONTINUWUITY_CONFIG=/etc/continuwuity.toml
    volumes:
      - /srv/continuwuity:/var/lib/continuwuity
      - ./continuwuity.toml:/etc/continuwuity.toml:ro
    restart: unless-stopped
    command:
      - /sbin/conduwuit
    labels:
      - glance.icon=sh:continuwuity-light
      - glance.id=continuwuity
      - glance.name=Continuwuity
      - traefik.enable=true
      - traefik.http.routers.continuwuity.entrypoints=websecure
      - traefik.http.routers.continuwuity.rule=Host(`chat.ocd.beauty`)
      - traefik.http.routers.continuwuity.tls.certresolver=letsencrypt
      - traefik.http.services.continuwuity.loadbalancer.server.port=8008

  lk-jwt-service:
    <<: *default-logging
    image: ghcr.io/element-hq/lk-jwt-service:0.7.0
    container_name: lk-jwt-service
    environment:
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=chat.ocd.beauty
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_URL=wss://rtc.chat.ocd.beauty
    restart: unless-stopped
    labels:
      - glance.name=lk-jwt-service
      - glance.parent=continuwuity
      - traefik.enable=true
      - traefik.http.routers.lk-jwt-service.entrypoints=websecure
      - traefik.http.routers.lk-jwt-service.rule=Host(`jwt.rtc.chat.ocd.beauty`)
      - traefik.http.routers.lk-jwt-service.tls.certresolver=letsencrypt
      - traefik.http.services.lk-jwt-service.loadbalancer.server.port=8080

  livekit-server:
    <<: *default-logging
    image: livekit/livekit-server:v1.13.6
    container_name: livekit-server
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    restart: unless-stopped
    command:
      - --config=/etc/livekit.yaml
    labels:
      - glance.name=livekit-server
      - glance.parent=continuwuity
      - traefik.enable=true
      - traefik.http.routers.livekit-server.entrypoints=websecure
      - traefik.http.routers.livekit-server.rule=Host(`rtc.chat.ocd.beauty`)
      - traefik.http.routers.livekit-server.tls.certresolver=letsencrypt
      - traefik.http.services.livekit-server.loadbalancer.server.port=7880

networks:
  default:
    external: true
    name: proxy
