x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  unbound:
    <<: *default-logging
    container_name: unbound
    image: madnuttah/unbound:1.26.1-0
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.20
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf:ro
    labels:
      - glance.parent=continuwuity
      - glance.name=unbound

  continuwuity:
    <<: *default-logging
    container_name: continuwuity
    image: forgejo.ellis.link/continuwuation/continuwuity:sha-c6f2c5e-maxperf
    restart: unless-stopped
    depends_on:
      - unbound
    command:
      - /sbin/conduwuit
    environment:
      - CONTINUWUITY_ALLOW_REGISTRATION=${CONTINUWUITY_ALLOW_REGISTRATION}
      - CONTINUWUITY_CONFIG=/etc/continuwuity.toml
    volumes:
      - ./continuwuity-resolv.conf:/etc/resolv.conf:ro
      - ./continuwuity.toml:/etc/continuwuity.toml:ro
      - /run/continuwuity:/run/continuwuity
      - /srv/continuwuity:/var/lib/continuwuity
    labels:
      - glance.name=Continuwuity
      - glance.icon=sh:continuwuity
      - glance.id=continuwuity
      - traefik.enable=true
      - traefik.http.routers.continuwuity.rule=Host(`matrix.ocd.beauty`)
      - traefik.http.routers.continuwuity.entrypoints=websecure
      - traefik.http.routers.continuwuity.tls.certresolver=letsencrypt
      - traefik.http.services.continuwuity.loadbalancer.server.port=8080

  lk-jwt-service:
    <<: *default-logging
    container_name: lk-jwt-service
    image: ghcr.io/element-hq/lk-jwt-service:0.7.0
    restart: unless-stopped
    environment:
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=matrix.ocd.beauty
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_URL=wss://rtc.matrix.ocd.beauty
    labels:
      - glance.parent=continuwuity
      - glance.name=lk-jwt-service
      - traefik.enable=true
      - traefik.http.routers.lk-jwt-service.rule=Host(`jwt.rtc.matrix.ocd.beauty`)
      - traefik.http.routers.lk-jwt-service.entrypoints=websecure
      - traefik.http.routers.lk-jwt-service.tls.certresolver=letsencrypt
      - traefik.http.services.lk-jwt-service.loadbalancer.server.port=8080

  livekit-server:
    <<: *default-logging
    container_name: livekit-server
    image: livekit/livekit-server:v1.13.6
    restart: unless-stopped
    command:
      - --config=/etc/livekit.yaml
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    labels:
      - glance.parent=continuwuity
      - glance.name=livekit-server
      - traefik.enable=true
      - traefik.http.routers.livekit-server.rule=Host(`rtc.matrix.ocd.beauty`)
      - traefik.http.routers.livekit-server.entrypoints=websecure
      - traefik.http.routers.livekit-server.tls.certresolver=letsencrypt
      - traefik.http.services.livekit-server.loadbalancer.server.port=7880

networks:
  default:
    name: proxy
    external: true
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
