x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  unbound:
    <<: *default-logging
    container_name: unbound
    image: madnuttah/unbound:1.26.1-0
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.20
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf:ro

  continuwuity:
    <<: *default-logging
    container_name: continuwuity
    image: forgejo.ellis.link/continuwuation/continuwuity:sha-c6f2c5e-maxperf
    restart: unless-stopped
    depends_on:
      - unbound
    command:
      - /sbin/conduwuit
    environment:
      - CONTINUWUITY_ALLOW_REGISTRATION=${CONTINUWUITY_ALLOW_REGISTRATION}
      - CONTINUWUITY_CONFIG=/etc/continuwuity.toml
    volumes:
      - ./continuwuity-resolv.conf:/etc/resolv.conf:ro
      - ./continuwuity.toml:/etc/continuwuity.toml:ro
      - /run/continuwuity:/run/continuwuity
      - /srv/continuwuity:/var/lib/continuwuity

  lk-jwt-service:
    <<: *default-logging
    container_name: lk-jwt-service
    image: ghcr.io/element-hq/lk-jwt-service:0.7.0
    restart: unless-stopped
    environment:
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=matrix.ocd.beauty
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_URL=wss://livekit.ocd.beauty

  livekit-server:
    <<: *default-logging
    container_name: livekit-server
    image: livekit/livekit-server:v1.13.6
    restart: unless-stopped
    command:
      - --config=/etc/livekit.yaml
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro

networks:
  default:
    name: proxy
    external: true
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
