x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  continuwuity:
    <<: *default-logging
    container_name: continuwuity
    image: forgejo.ellis.link/continuwuation/continuwuity:sha-c6f2c5e-maxperf
    restart: unless-stopped
    command:
      - /sbin/conduwuit
    environment:
      - CONTINUWUITY_ALLOW_REGISTRATION=${CONTINUWUITY_ALLOW_REGISTRATION}
      - CONTINUWUITY_CONFIG=/etc/continuwuity.toml
    volumes:
      - ./continuwuity.toml:/etc/continuwuity.toml:ro
      - /bin/busybox:/busybox:ro
      - /run/continuwuity:/run/continuwuity
      - /srv/continuwuity:/var/lib/continuwuity
    healthcheck:
      test: ["CMD", "/busybox", "test", "-S", "/run/continuwuity/continuwuity.sock"]

  lk-jwt-service:
    <<: *default-logging
    container_name: lk-jwt-service
    image: ghcr.io/element-hq/lk-jwt-service:latest
    restart: unless-stopped
    environment:
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=matrix.ocd.beauty
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_URL=wss://livekit.ocd.beauty

  livekit:
    <<: *default-logging
    container_name: livekit
    image: livekit/livekit-server:v1.13.6
    restart: unless-stopped
    command:
      - --config=/etc/livekit.yaml
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_KEY}: ${LIVEKIT_SECRET}"
      - LIVEKIT_NODE=${LIVEKIT_NODE}
    network_mode: host
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "7880"]

networks:
  default:
    name: proxy
    external: true
