[global]
allow_federation = false
database_path = "/var/lib/continuwuity"
request_ip_source = "x_forwarded_for"
server_name = "matrix.ocd.beauty"
unix_socket_path = "/run/continuwuity/continuwuity.sock"
unix_socket_perms = 0o777

[global.well_known]
client = "https://matrix.ocd.beauty"
server = "matrix.ocd.beauty:443"
support_email = "320689555+losi57304@users.noreply.github.com"

[global.matrix_rtc]
foci = [
    { type = "livekit", livekit_service_url = "https://livekit.ocd.beauty" },
]
