x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  metrics-beszel:
    <<: *default-logging
    container_name: metrics-beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    volumes:
      - /run/beszel:/beszel_socket
      - /srv/beszel/data:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]

  metrics-beszel-agent:
    <<: *default-logging
    container_name: metrics-beszel-agent
    image: henrygd/beszel-agent:0.19.0
    restart: unless-stopped
    environment:
      - HUB_URL=http://metrics-beszel:8090
      - KEY=${BESZEL_AGENT_KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_AGENT_TOKEN}
    volumes:
      - /run/beszel:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - metrics-beszel
    healthcheck:
      test: ["CMD", "/agent", "health"]

networks:
  default:
    name: proxy
    external: true
