x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  dufs:
    <<: *default-logging
    container_name: dufs
    image: sigoden/dufs:v0.46.0
    restart: unless-stopped
    command:
      - --allow-all
      - --auth=${DUFS_USERNAME}:${DUFS_PASSWORD}@/:rw
      - /music
    volumes:
      - /run/dufs:/run/dufs
      - /srv/gonic/music:/music
    labels:
      - glance.name=Dufs
      - glance.icon=sh:dufs.png
      - glance.url=https://files.music.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.dufs.rule=Host(`files.music.ocd.beauty`)
      - traefik.http.routers.dufs.entrypoints=websecure
      - traefik.http.routers.dufs.tls.certresolver=letsencrypt
      - traefik.http.services.dufs.loadbalancer.server.port=8090

  gonic:
    <<: *default-logging
    container_name: gonic
    image: sentriz/gonic:8df10c3
    restart: unless-stopped
    environment:
      - GONIC_CACHE_PATH=/cache
      - GONIC_DB_PATH=/data/gonic.db
      - GONIC_MUSIC_PATH=/music
      - GONIC_PLAYLISTS_PATH=/playlists
      - GONIC_PODCAST_PATH=/podcast
    volumes:
      - /srv/gonic/cache:/cache
      - /srv/gonic/data:/data
      - /srv/gonic/music:/music
      - /srv/gonic/playlists:/playlists
      - /srv/gonic/podcast:/podcast
    labels:
      - glance.name=Gonic
      - glance.icon=sh:gonic.png
      - glance.url=https://music.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.gonic.rule=Host(`music.ocd.beauty`)
      - traefik.http.routers.gonic.entrypoints=websecure
      - traefik.http.routers.gonic.tls.certresolver=letsencrypt
      - traefik.http.services.gonic.loadbalancer.server.port=80

networks:
  default:
    name: proxy
    external: true
