x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  copyparty:
    <<: *default-logging
    image: copyparty/ac:1.20.24
    container_name: copyparty
    volumes:
      - /srv/copyparty/cfg:/cfg
      - /srv/navidrome/music:/w
    restart: unless-stopped
    command:
      - -v
      - /w::rwmda
    labels:
      - glance.icon=sh:copyparty-light
      - glance.name=Copyparty
      - glance.url=https://files.music.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.copyparty.entrypoints=websecure
      - traefik.http.routers.copyparty.rule=Host(`files.music.ocd.beauty`)
      - traefik.http.routers.copyparty.tls.certresolver=letsencrypt
      - traefik.http.services.copyparty.loadbalancer.server.port=3923

  navidrome:
    <<: *default-logging
    image: deluan/navidrome:latest
    container_name: navidrome
    volumes:
      - /srv/navidrome/data:/data
      - /srv/navidrome/music:/music:ro
    restart: unless-stopped
    labels:
      - glance.icon=sh:navidrome-light
      - glance.name=Navidrome
      - glance.url=https://music.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.gonic.rule=Host(`music.ocd.beauty`)
      - traefik.http.routers.gonic.entrypoints=websecure
      - traefik.http.routers.gonic.tls.certresolver=letsencrypt
      - traefik.http.services.gonic.loadbalancer.server.port=4533

networks:
  default:
    external: true
    name: proxy
