x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  monitoring-beszel:
    <<: *default-logging
    container_name: monitoring-beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    volumes:
      - /run/beszel:/beszel_socket
      - /srv/beszel/data:/beszel_data
    labels:
      - homepage.group=Monitoring
      - homepage.name=Beszel
      - homepage.href=https://monitoring.ocd.beauty
      - homepage.description=Media server

  monitoring-beszel-agent:
    <<: *default-logging
    container_name: monitoring-beszel-agent
    image: henrygd/beszel-agent:0.19.0
    restart: unless-stopped
    depends_on:
      - monitoring-beszel
    environment:
      - HUB_URL=http://monitoring-beszel:8090
      - KEY=${BESZEL_AGENT_KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_AGENT_TOKEN}
    volumes:
      - /run/beszel:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: proxy
    external: true
