x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  beszel:
    <<: *default-logging
    image: henrygd/beszel:0.19.0
    container_name: beszel
    volumes:
      - /run/beszel:/beszel_socket
      - /srv/beszel/data:/beszel_data
    restart: unless-stopped
    labels:
      - glance.icon=sh:beszel
      - glance.id=beszel
      - glance.name=Beszel
      - glance.url=https://monitoring.ocd.beauty
      - traefik.enable=true
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.rule=Host(`monitoring.ocd.beauty`)
      - traefik.http.routers.beszel.tls.certresolver=letsencrypt
      - traefik.http.services.beszel.loadbalancer.server.port=8090

  beszel-agent:
    <<: *default-logging
    image: henrygd/beszel-agent:0.19.0
    container_name: beszel-agent
    depends_on:
      - beszel
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=${BESZEL_AGENT_KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_AGENT_TOKEN}
    volumes:
      - /run/beszel:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - glance.name=beszel-agent
      - glance.parent=beszel

networks:
  default:
    external: true
    name: proxy
